<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-02 at 18:48:16.
 */

require_once '../../includes/databaseClass.php';

class databaseTest extends PHPUnit_Extensions_Database_TestCase {

    /**
     * @var database
     */
    protected $object;
    static private $pdo = NULL;
    private $conn = NULL;


    protected function setUp() {
        $this->object = new database('mysql','localhost','mobileProgrammeUnitTest','root','parsedto');
    }

    protected function tearDown() {
        
    }
    
    public function getConnection()
    {
        if ($this->conn === NULL) {
            if (self::$pdo == NULL) {
                self::$pdo = new PDO(
                        $GLOBALS['driver'],
                        $GLOBALS['host'],
                        $GLOBALS['database'],
                        $GLOBALS['user'],
                        $GLOBALS['password']
                        );
            }
            $this->conn = $this->createDefaultDBConnection(self::$pdo, $GLOBALS['database']);
        }

        return $this->conn;
    }
    
    public function getDataSet()
    {
        return $this->createMySQLXMLDataSet('../programmeSuperByte.xml');
    }
    
    

    /**
     * @covers database::execSQL
     * @todo   Implement testExecSQL().
     */
    public function testExecSQL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers database::returnResult
     * @todo   Implement testReturnResult().
     */
    public function testReturnResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
