<?php

require_once __DIR__ . '/../../includes/programmeClass.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-22 at 21:23:31.
 */
class programmeTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var programme
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new programme();
    }

    /**
     * @covers programme::getDBVersion
     * @todo   Implement testGetDBVersion().
     */
    public function testGetDBVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers programme::getAppVersion
     * @todo   Implement testGetAppVersion().
     */
    public function testGetAppVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers programme::getYouTubeIds
     * @todo   Implement testGetYouTubeIds().
     */
    public function testGetYouTubeIds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers programme::getAllData
     * @todo   Implement testGetAllData().
     */
    public function testGetAllData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
